CREATE TABLE IF NOT EXISTS accounts (
    id VARCHAR(255) NOT NULL primary key COMMENT 'primary key', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', name varchar(255) COMMENT 'User Name', email varchar(255) COMMENT 'User Email', picture varchar(255) COMMENT 'User Picture'
) default charset utf8mb4 COMMENT '';

CREATE TABLE recipes (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', title VARCHAR(60) NOT NULL, instructions VARCHAR(500), img VARCHAR(1000), category VARCHAR(60), archived BOOLEAN NOT NULL DEFAULT false, creatorId VARCHAR(255), FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
)

CREATE TABLE ingredients (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', name VARCHAR(60) NOT NULL, quantity VARCHAR(255), recipeId INT NOT NULL, creatorId VARCHAR(255), FOREIGN KEY (recipeId) REFERENCES recipes (id) ON DELETE CASCADE
)

CREATE TABLE favorites (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', recipeId INT NOT NULL, accountId VARCHAR(255) NOT NULL, FOREIGN KEY (recipeId) REFERENCES recipes (id) ON DELETE CASCADE, FOREIGN KEY (accountId) REFERENCES accounts (id) ON DELETE CASCADE
)

DROP TABLE recipes;

SELECT recipe.*, account.*
FROM
    recipes recipe
    JOIN accounts account ON recipe.creatorId = account.id;